import { Button, VerticalBox, Palette } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 500px;
    height: 140px;  
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Enter Your Holesail Code Below (hs://...)";
            horizontal-alignment: center;
            vertical-alignment: center;
            font-weight: 700;
            font-size: 15px;
        }
        Rectangle {
            height: 40px;
            border-radius: 16px;
            background: gray;
            VerticalBox {
                padding: 11px;
                TextInput {
                    color: black;
                    font-weight: 700;
                }
            }
        }

        Button {
            height: 40px;
            text: "Connect";
        }
    }
}
