import { Button, VerticalBox, Palette, HorizontalBox, Switch, ProgressIndicator } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 500px;
    height: 190px;  
    title: "Porthole";
    in-out property <int> activepage: 0;
    in-out property <float> loadingbar: 0.0;
    in-out property <string> loadingtext: "Loading...";
    callback request-increase-value();
    if (activepage == 1) : VerticalBox {
        Text {
            text: "Enter Your Holesail Code Below (hs://...)";
            horizontal-alignment: center;
            vertical-alignment: center;
            font-weight: 700;
            font-size: 15px;
        }
        Rectangle {
            height: 40px;
            border-radius: 16px;
            background: gray;
            VerticalBox {
                padding: 11px;
                TextInput {
                    color: black;
                    font-weight: 700;
                }
            }
        }

        HorizontalBox {
            height: 50px;
            padding: 2px;
            
            HorizontalBox {
                width: 250px;
                padding-right: 100px;
                
                Text {
                    text: "Port (Optional)";
                    vertical-alignment: center;
                }
                Rectangle {
                    height: 30px;
                    border-radius: 16px;
                    background: gray;
                    width: 100px;
                    
                }
            }
            HorizontalBox {
                padding-right: 120px;
                width: 250px;
                Text {
                    text: "Start On Boot? (WIP)";
                    vertical-alignment: center;
                }
                Switch {
                    enabled: false;
                }
            }
        }

        Button {
            height: 40px;
            text: "Connect";
        }
    }
    if (activepage == 0) :  VerticalBox {
        padding: 20px;
        Text {
            text: root.loadingtext;
            font-weight: 700;
            font-size: 20px;
            vertical-alignment: center;
            horizontal-alignment: center;
            wrap: word-wrap;
        }
        // ProgressIndicator {
        //     progress: root.loadingbar;
        //     height: 6px;
            
            
        //  }
    }
}
